version: '3.8'

services:
  mongo-db:
    image: mongo:6.0
    container_name: empleados_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api-empleados:
    build: .
    container_name: empleados_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27018/empleadosDB
    volumes:
      - .:/app
    depends_on:
      - mongo-db
    command: npm start

volumes:
  mongo_data:
