version: "3.8"

services:
  mongo-db:
    image: mongo:7.0
    container_name: empleados_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-empleados:
    build: .
    container_name: empleados_api
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/empleadosDB
    volumes:
      - .:/app
    depends_on:
      - mongo-db
    command: npm run dev

volumes:
  mongo_data:
